site_name: Sematido
site_url: https://hikarilabs.github.io/semantido/
copyright: Copyright &copy; 2026 Dragos Crintea

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]
          options:
            allow_inspection: true
  - search
  - blog:
      blog_dir: blog
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/slug"
      authors_file: "{blog}/.authors.yml"


nav:
  - Index: index.md
  - Why Semantido: explanation.md
  - Examples:
    - 01 - Getting Started: examples/01_getting_started.md
  - Code Reference: reference.md
  - Tutorials: blog/index.md
